/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sopadeletras.BuscarPalabra;
import sopadeletras.MatrizTablero;
import sopadeletras.Grafo;
import sopadeletras.ListaPalabra;
import sopadeletras.ListaSimple;

/**
 *
 * @author alexandraloynaz
 */
public class Ventana3 extends javax.swing.JFrame {
public MatrizTablero tablero;
public Grafo grafo;
private boolean EsBFS;
    /**
     * Creates new form Ventana3
     */
    public Ventana3(MatrizTablero tablero, ListaPalabra diccionario) {
        tablero.conectarNodos();
        initComponents();
        setSize(500,540);
        this.tablero = tablero;
        mostrarTablero(tablero);
        grafo = new Grafo(tablero);
        
        grafo.mostrarGrafo();
        

        
       ImageIcon buscarPalabra = new ImageIcon(getClass().getResource("/Imagenes/BotonBuscarPalabra.png"));
       botonBuscarPalabra.setIcon(buscarPalabra);
//

//
        ImageIcon imagenFondo= new ImageIcon(getClass().getResource("/Imagenes/FondoVentana3.png"));
        JLabel fondo = new JLabel(imagenFondo);
       getContentPane().add(fondo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
//        VerificacionTXT.setText("");
    cuadroDiccionario.setText(diccionario.mostrar());
        
    }
    public void mostrarTablero(MatrizTablero tablero){
        int tamanoCelda=65;
        MostrarTablero.removeAll();
            for (int fila = 0; fila < 4; fila++) {
                for (int columna = 0; columna < 4; columna++) {
                char letra= tablero.obtenerNodo(fila, columna).getLetra();
                JLabel celda = new JLabel(String.valueOf(letra),javax.swing.SwingConstants.CENTER);
                MostrarTablero.add(celda, new org.netbeans.lib.awtextra.AbsoluteConstraints(columna*tamanoCelda, fila*tamanoCelda, tamanoCelda, tamanoCelda));
            }
            
        }
        MostrarTablero.repaint();
        MostrarTablero.revalidate();
    
    
    }
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonBSF = new javax.swing.JRadioButton();
        BotonDSF = new javax.swing.JRadioButton();
        botonBuscarPalabra = new javax.swing.JButton();
        palabra = new javax.swing.JTextField();
        respuesta = new javax.swing.JTextField();
        MostrarTablero = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroDiccionario = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBSFActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        BotonDSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDSFActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        botonBuscarPalabra.setText("Agregar palabra");
        botonBuscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPalabraActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 210, 40));

        palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraActionPerformed(evt);
            }
        });
        getContentPane().add(palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 140, -1));

        respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaActionPerformed(evt);
            }
        });
        getContentPane().add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 230, -1));

        MostrarTablero.setBackground(new java.awt.Color(237, 209, 186));
        MostrarTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MostrarTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, 200));

        cuadroDiccionario.setColumns(20);
        cuadroDiccionario.setRows(5);
        jScrollPane1.setViewportView(cuadroDiccionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBSFActionPerformed
        // TODO add your handling code here:
        this.EsBFS = true;
        
        
    }//GEN-LAST:event_BotonBSFActionPerformed

    private void palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraActionPerformed
        // TODO add your handling code here:
        String palabraBuscando = palabra.getText(); 
        if (palabraBuscando.trim().length()<3){
            JOptionPane.showMessageDialog(null, "La palabra debe tener minimo 3 letras ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_palabraActionPerformed

    private void respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaActionPerformed

    private void botonBuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPalabraActionPerformed
        // TODO add your handling code here:
        BuscarPalabra busqueda = new BuscarPalabra(tablero);
        String p = palabra.getText();
        ListaSimple Lista = null;
        if(this.EsBFS){
            Lista = busqueda.BFSInicio(p);
        } else{
            //AÑADIR CODIGO DE BUSQUEDA DFS AQUI
        }
        if(Lista!=null){
            grafo.mostrarPalabra(Lista);
        } else{
            JOptionPane.showMessageDialog(null, "La palabra no existe en la sopa de letras");
        }
        grafo.mostrarGrafo();
    }//GEN-LAST:event_botonBuscarPalabraActionPerformed

    private void BotonDSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDSFActionPerformed
        // TODO add your handling code here:
        this.EsBFS = false;
    }//GEN-LAST:event_BotonDSFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3(tablero).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonBSF;
    private javax.swing.JRadioButton BotonDSF;
    private java.awt.Panel MostrarTablero;
    private javax.swing.JButton botonBuscarPalabra;
    private javax.swing.JTextArea cuadroDiccionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField palabra;
    private javax.swing.JTextField respuesta;
    // End of variables declaration//GEN-END:variables
}
