/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sopadeletras.BuscarPalabra;
import sopadeletras.MatrizTablero;
import sopadeletras.Grafo;
import sopadeletras.ListaPalabra;
import sopadeletras.ListaSimple;

/**
 * Ventana que muestra el tablero de a sopa de letras, permite buscar palabras y visualizar la ruta segun dos algoritmos.
 * @author alexandraloynaz
 */
public class Ventana3 extends javax.swing.JFrame {
public MatrizTablero tablero;
private ListaPalabra diccionario;
public Grafo grafo;
private boolean EsBFS;
private boolean EsDFS;
 private BuscarPalabra buscador;
    /**
     * Contructor que genera una instancia de ventana3 con el tablero y diccionario especifico 
     * @param tablero el tablero con todas las letras
     * @param diccionario lista de palabras que se encuentran en este tablero. 
     */
    public Ventana3(MatrizTablero tablero, ListaPalabra diccionario) {
        tablero.conectarNodos();
        initComponents();
        setSize(500,540);
        this.tablero = tablero;
        this.diccionario=diccionario;
        mostrarTablero(tablero);
        grafo = new Grafo(tablero);
        buscador = new BuscarPalabra(tablero);
        grafo.mostrarGrafo();
        

        
       ImageIcon buscarPalabra = new ImageIcon(getClass().getResource("/Imagenes/BotonBuscarPalabra.png"));
       botonBuscarPalabra.setIcon(buscarPalabra);
       ImageIcon botonReestablecer = new ImageIcon(getClass().getResource("/Imagenes/BotonReestablecer.png"));
       BotonReestablecer.setIcon(botonReestablecer);
//

//
        ImageIcon imagenFondo= new ImageIcon(getClass().getResource("/Imagenes/FondoVentana3.png"));
        JLabel fondo = new JLabel(imagenFondo);
       getContentPane().add(fondo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
//        VerificacionTXT.setText("");
    cuadroDiccionario.setText(diccionario.mostrar());
        
    }
    /** 
     * Muestra el tablero en la interfaz
     * @param tablero el tablero que se desea mostrar
     */
    public void mostrarTablero(MatrizTablero tablero){
        int tamanoCelda=65;
        MostrarTablero.removeAll();
            for (int fila = 0; fila < 4; fila++) {
                for (int columna = 0; columna < 4; columna++) {
                char letra= tablero.obtenerNodo(fila, columna).getLetra();
                JLabel celda = new JLabel(String.valueOf(letra),javax.swing.SwingConstants.CENTER);
                MostrarTablero.add(celda, new org.netbeans.lib.awtextra.AbsoluteConstraints(columna*tamanoCelda, fila*tamanoCelda, tamanoCelda, tamanoCelda));
            }
            
        }
        MostrarTablero.repaint();
        MostrarTablero.revalidate();
    
    
    }
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonBSF = new javax.swing.JRadioButton();
        BotonDSF = new javax.swing.JRadioButton();
        botonBuscarPalabra = new javax.swing.JButton();
        palabra = new javax.swing.JTextField();
        respuesta = new javax.swing.JTextField();
        MostrarTablero = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroDiccionario = new javax.swing.JTextArea();
        BotonReestablecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBSFActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(BotonDSF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        botonBuscarPalabra.setText("Agregar palabra");
        getContentPane().add(botonBuscarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 210, 40));

        palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraActionPerformed(evt);
            }
        });
        getContentPane().add(palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 140, -1));

        respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaActionPerformed(evt);
            }
        });
        getContentPane().add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 230, -1));

        MostrarTablero.setBackground(new java.awt.Color(237, 209, 186));
        MostrarTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(MostrarTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, 200));

        cuadroDiccionario.setColumns(20);
        cuadroDiccionario.setRows(5);
        jScrollPane1.setViewportView(cuadroDiccionario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, 120));

        BotonReestablecer.setText("Reestablecer");
        BotonReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReestablecerActionPerformed(evt);
            }
        });
        getContentPane().add(BotonReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 10, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Asegura que solo la opcion de BSF se encuntra activada
 * @param evt 
 */
    private void BotonBSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBSFActionPerformed
        // TODO add your handling code here:
        this.EsBFS = true;
        this.EsDFS = false;
        
        
    }//GEN-LAST:event_BotonBSFActionPerformed
/** 
 * Valida la palabra ingresada.
 * @param evt 
 */
    private void palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraActionPerformed
        // TODO add your handling code here:
        String palabraBuscando = palabra.getText(); 
        if (palabraBuscando.trim().length()<3){
            JOptionPane.showMessageDialog(null, "La palabra debe tener minimo 3 letras ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_palabraActionPerformed

    private void respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaActionPerformed
/**
 * Realiza la busqueda de la palabra cuando se presiona el botón, también se actualiza el diccionario si la palabra se encuntra en el tablero.
 * @param evt 
 */
    private void botonBuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPalabraActionPerformed
        // TODO add your handling code here:
        String palabraBuscando = palabra.getText().trim().toUpperCase();
        boolean enDiccionario = diccionario.enDiccionario(palabraBuscando);
        boolean enTablero = buscador.existePalabraDFS(palabraBuscando);
        if(!enDiccionario && enTablero){
            JOptionPane.showMessageDialog(null, "La palabra no se encuentra en el diccionario pero si en el tablero, ahora se va a agregar");
            diccionario.insertarFinal(palabraBuscando);
            cuadroDiccionario.setText(diccionario.mostrar());
        BuscarPalabra busqueda = new BuscarPalabra(tablero);
        
        ListaSimple ruta = null;
        if(this.EsBFS){
            ruta = busqueda.BFSInicio(palabraBuscando);
        } else{
            ruta = busqueda.rutaDFS(palabraBuscando);
            
            
        }
        if(ruta!=null){
            grafo.limpiar();
            grafo.mostrarPalabra(ruta);
            respuesta.setText("Palabra encontrada: "+ palabraBuscando);
        } else{
            respuesta.setText("La palabra no existe en la sopa de letras");
        }
        }

    }//GEN-LAST:event_botonBuscarPalabraActionPerformed
/**
 * Asegura que solo la opcion de DSF se encuntra activada
 * @param evt 
 */
    private void BotonDSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDSFActionPerformed
        // TODO add your handling code here:
        this.EsBFS = false;
        this.EsDFS= true; 
    }//GEN-LAST:event_BotonDSFActionPerformed

    private void BotonReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReestablecerActionPerformed
       palabra.setText("");
      respuesta.setText("");
      BotonBSF.setSelected(false);
       BotonDSF.setSelected(false);
         this.EsBFS=false; 
       this.EsDFS= false;
       grafo.limpiar();
       JOptionPane.showMessageDialog(null, "Puede comenzar a buscar una nueva palabra");

    }//GEN-LAST:event_BotonReestablecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3(tablero).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonBSF;
    private javax.swing.JRadioButton BotonDSF;
    private javax.swing.JButton BotonReestablecer;
    private java.awt.Panel MostrarTablero;
    private javax.swing.JButton botonBuscarPalabra;
    private javax.swing.JTextArea cuadroDiccionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField palabra;
    private javax.swing.JTextField respuesta;
    // End of variables declaration//GEN-END:variables
}
